"""empty message

Revision ID: f04eebdeb002
Revises:
Create Date: 2020-05-25 09:54:58.472924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04eebdeb002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',

    sa.Column('id', sa.Integer(), nullable=False),

    sa.Column('name', sa.String(), nullable=True),

    op.execute("UPDATE artist SET name = False WHERE name IS NULL;"),

    op.alter_column('Artist', 'name', nullable=False),

    sa.Column('city', sa.String(length=120), nullable=True),

    op.execute("UPDATE artist SET city = False WHERE city IS NULL;"),

    op.alter_column('Artist', 'city', nullable=True),

    sa.Column('state', sa.String(length=120), nullable=True),

    op.execute("UPDATE artist SET state = False WHERE state IS NULL;"),

    op.alter_column('Artist', 'state', nullable=False),

    sa.Column('phone', sa.String(length=120), nullable=True),

    op.execute("UPDATE artist SET phone = False WHERE phone IS NULL;"),

    op.alter_column('Artist', 'phone', nullable=False),

    sa.Column('genres', sa.String(length=120), nullable=True),

    op.execute("UPDATE Artist SET genres = False WHERE genres IS NULL;"),

    op.alter_column('Artist', 'genres', nullable=False),

    sa.Column('image_link', sa.String(length=500), nullable=True),

    op.execute("UPDATE artist SET image_link = False WHERE image_link IS NULL;"),

    op.alter_column('Artist', 'image_link', nullable=False),

    sa.Column('facebook_link', sa.String(length=120), nullable=True),

    op.execute("UPDATE artist SET facebook_link = False WHERE facebook_link IS NULL;"),

    op.alter_column('Artist', 'facebook_link', nullable=False),

    sa.Column('website', sa.String(length=120), nullable=True),

    op.execute("UPDATE artist SET website = False WHERE website IS NULL;"),

    op.alter_column('Artist', 'website', nullable=False),

    sa.Column('seeking_venues', sa.Boolean(), nullable=True),

    op.execute("UPDATE artist SET seeking_venues = False WHERE seeking_venues IS NULL;"),

    op.alter_column('Artist', 'seeking_venues', nullable=False),

    sa.Column('seeking_description', sa.String(length=300), nullable=True),

    op.execute("UPDATE artist SET seeking_description = False WHERE seeking_description IS NULL;"),

    op.alter_column('Artist', 'seeking_description', nullable=False),

    sa.Column('past_shows', sa.String(length=500), nullable=True),

    op.execute("UPDATE artist SET past_shows = False WHERE past_shows IS NULL;"),

    op.alter_column('Artist', 'past_shows', nullable=False),

    sa.Column('upcoming_shows', sa.String(length=500), nullable=True),

    op.execute("UPDATE artist SET upcoming_shows= False WHERE upcoming_shows IS NULL;"),

    op.alter_column('Artist', 'upcoming_shows', nullable=False),

    sa.Column('past_shows_count', sa.Integer(), nullable=True),

    op.execute("UPDATE artist SET past_shows_count= False WHERE past_shows_count IS NULL;"),

    op.alter_column('Artist', 'past_shows_count', nullable=False),

    sa.Column('upcoming_shows_count', sa.Integer(), nullable=True),

    op.execute("UPDATE artist SET upcoming_shows_count= False WHERE upcoming_shows_count IS NULL;"),

    op.alter_column('Artist', 'upcoming_shows_count', nullable=False),



    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),

    op.execute('UPDATE "Venue" SET name= False WHERE name IS NULL;'),

    op.alter_column('Venue', 'name', nullable=False),

    sa.Column('city', sa.String(length=120), nullable=True),

    op.execute('UPDATE "Venue" SET city= False WHERE city IS NULL;'),

    op.alter_column('Venue', 'city', nullable=False),

    sa.Column('state', sa.String(length=120), nullable=True),

    op.execute('UPDATE "Venue" SET state= False WHERE state IS NULL;'),

    op.alter_column('Venue', 'state', nullable=False),

    sa.Column('address', sa.String(length=120), nullable=True),

    op.execute('UPDATE "Venue" SET address= False WHERE address IS NULL;'),

    op.alter_column('Venue', 'address', nullable=False),

    sa.Column('phone', sa.String(length=120), nullable=True),

    op.execute('UPDATE Venue SET phone= False WHERE phone IS NULL;'),

    op.alter_column('Venue', 'phone', nullable=False),

    sa.Column('genres', sa.String(length=120), nullable=True),

    op.execute('UPDATE Venue SET genres= False WHERE genres IS NULL;'),

    op.alter_column('Venue', 'genres', nullable=False),

    sa.Column('image_link', sa.String(length=500), nullable=True),

    op.execute('UPDATE Venue SET image_link= False WHERE image_link IS NULL;'),

    op.alter_column('Venue', 'image_link', nullable=False),

    sa.Column('facebook_link', sa.String(length=120), nullable=True),

    op.execute('UPDATE Venue SET facebook_link= False WHERE facebook_link IS NULL;'),

    op.alter_column('Venue', 'facebook_link', nullable=False),

    sa.Column('website', sa.String(length=120), nullable=True),

    op.execute('UPDATE Venue SET website= False WHERE website IS NULL;'),

    op.alter_column('Venue', 'website', nullable=False),

    sa.Column('seeking_description', sa.String(length=300), nullable=True),

    op.execute('UPDATE Venue SET seeking_description= False WHERE seeking_description IS NULL;'),

    op.alter_column('Venue', 'seeking_description', nullable=False),

    sa.Column('seeking_talent', sa.Boolean(), nullable=True),

    op.execute('UPDATE Venue SET seeking_talent= False WHERE seeking_talent IS NULL;'),

    op.alter_column('Venue', 'seeking_talent', nullable=False),

    sa.Column('past_shows', sa.String(length=500), nullable=True),

    op.execute('UPDATE Venue SET past_shows= False WHERE past_shows IS NULL;'),

    op.alter_column('Venue', 'past_shows', nullable=False),

    sa.Column('upcoming_shows', sa.String(length=500), nullable=True),

    op.execute('UPDATE Venue SET upcoming_shows= False WHERE upcoming_shows IS NULL;'),

    op.alter_column('Venue', 'upcoming_shows', nullable=False),

    sa.Column('past_shows_count', sa.Integer(), nullable=True),

    op.execute('UPDATE Venue SET past_shows_count= False WHERE past_shows_count IS NULL;'),

    op.alter_column('Venue', 'past_shows_count', nullable=False),

    sa.Column('upcoming_shows_count', sa.Integer(), nullable=True),

    op.execute('UPDATE Venue SET upcoming_shows_count= False WHERE upcoming_shows_count IS NULL;'),

    op.alter_column('Venue', 'upcoming_shows_count', nullable=False),

    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
